version: '3.4'

networks:
  dev:
    driver: bridge
services:
  erotion.api:
    image: ${DOCKER_REGISTRY-}erotionapi
    depends_on:
     - "erotion.database"
    build:
      context: .
      dockerfile: Erotion.API/Dockerfile
    ports:
      - "7261:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=7261
      - ASPNETCORE_URLS=https://+:443
    volumes:
      - D:\Erotion:/app/Files:rw
    networks:
      - dev
  erotion.database:
    image: postgres:latest
    container_name: erotion.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ErotionContext
    ports:
      - "5433:5432"
    volumes:
      - ./.containers/erotion_db:/var/lib/postgresql/data
    networks:
      - dev